USE master
GO

DROP DATABASE IF EXISTS C2109i1WF
CREATE DATABASE C2109i1WF
GO

USE C2109i1WF
GO

DROP TABLE  IF EXISTS Student
CREATE TABLE Student(
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR (50),
	LastName NVARCHAR(50),
	Gender BIT,
	Dob DATE
)
GO

INSERT INTO Student(FirstName,LastName,Gender,Dob) 
	VALUES ( N'Nghĩa',N'Hồ',1,'2003/04/27')
GO